language: ruby
bundler_args: --without development --deployment --jobs=3 --retry=10
cache: bundler
os:
  - osx
osx_image: xcode7.3
rvm: system
script:
  - RAILS_ENV=test bin/setup
  - RAILS_ENV=test bundle exec rake --trace spec
before_script:
  - psql -c 'create database fauna_development;' -U postgres
  - psql -c 'create database fauna_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
sudo: false
